### ISSUE TITLE
Make code slightly more rubyish

### ISSUE THREAD

**Issue by orlando-labs** [ankane/torch.rb#19]
Hi, @ankane, what do you think of the following ideas:

- [ ] renaming model-related methods :train and :eval to :train! and :eval! as the bang-methods looks semantically more correct in the context.
- [ ] adding alias :state_dict= to :load_state_dict

**Comment by ankane** [comment]
Thanks for the suggestions. This is a pretty subjective topic, but here are my initial thoughts:

- For `train` and `eval`, typically `!` means there's a non-`!` method, which isn't the case here
- For `load_state_dict`, it feels more like a method to me than a setter (there's also a `strict` option that's not implemented yet)

**Comment by mib32** [comment]
I'd also say that's not so important

**Comment by ankane** [comment]
Cleaning up issues
