### ISSUE TITLE
RuntimeError isGenericDict() INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by 007lva** [ankane/torch.rb#21]
Hello, I've got this error when try to load my model:

```
irb(main):001:0> Torch.load('model_ruby_v2.pth')
Traceback (most recent call last):
        1: from (irb):1
RuntimeError (isGenericDict() INTERNAL ASSERT FAILED at "../aten/src/ATen/core/ivalue_inl.h":923, please report a bug to PyTorch. Expected GenericDict but got None)
```

I've tried also pointing to the current master branch with the hope that changes from #18 fixes it but still get the same error. This model was generated with Python, Pytorch 10.1 and Cuda 10.1, I've tried with more versions but still can't get it working

**Comment by orlando-labs** [comment]
This is libtorch-related issue as the message says. I went through it several times. Before saving please convert python OrderedDict to common dict. Then it should load successfully.

**Comment by orlando-labs** [comment]
Hi, @ankane, what do you think of noticing this issue in readme as it is widespread with libtorch and we aren't able to fix it.

**Comment by 007lva** [comment]
Thanks @orlando-labs, it works!

**Comment by ankane** [comment]
Thanks @007lva  and @orlando-labs . Added a note to the readme to address both https://github.com/pytorch/pytorch/issues/37213 and https://github.com/pytorch/pytorch/issues/42651.

**Comment by mikeyEcology** [comment]
Following the response from @orlando-labs, I am doing this to save my models now in python when I plan to load them in R. 
```
torch.save(dict(model.to(device='cpu').state_dict()), path2weights)
```
