### ISSUE TITLE
compile of extension fails

### ISSUE THREAD

**Issue by MadBomber** [ankane/torch.rb#22]
13:14:51 3.0.0p0  s5:~ $ gem ins torch-rb
Building native extensions. This could take a while...
ERROR:  Error installing torch-rb:
	ERROR: Failed to build gem native extension.

    current directory: /Users/dewayne/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/torch-rb-0.6.0/ext/torch
/Users/dewayne/.rbenv/versions/3.0.0/bin/ruby -I /Users/dewayne/.rbenv/versions/3.0.0/lib/ruby/site_ruby/3.0.0 -r ./siteconf20210401-32375-3y09e9.rb extconf.rb
checking for -lstdc++... yes
checking for -lomp... yes
checking for -ltorch... yes
checking for -lmkldnn... no
checking for -lnnpack... no
Generating C++ functions...
creating Makefile

current directory: /Users/dewayne/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/torch-rb-0.6.0/ext/torch
make DESTDIR\= clean

current directory: /Users/dewayne/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/torch-rb-0.6.0/ext/torch
make DESTDIR\=
compiling cuda.cpp
compiling device.cpp
compiling ext.cpp
compiling ivalue.cpp
In file included from ivalue.cpp:5:
In file included from /Users/dewayne/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rice-3.0.0/ruby/lib/include/rice/Hash.hpp:227:
/Users/dewayne/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rice-3.0.0/ruby/lib/include/rice/Hash.ipp:197:21: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'long' [-Wsign-compare]
  if(current_index_ < hash_keys().size()) {
     ~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~
ivalue.cpp:129:25: note: in instantiation of member function 'Rice::Hash::Iterator<Rice::Hash &, Rice::Hash::Entry>::operator++' requested here
        for (auto entry : obj) {
                        ^
1 warning generated.
compiling nn.cpp
compiling nn_functions.cpp
compiling random.cpp
compiling ruby_arg_parser.cpp
compiling tensor.cpp
tensor.cpp:80:10: error: no member named '_backward' in 'at::Tensor'
    self._backward(inputs, gradient, retain_graph, create_graph);
    ~~~~ ^
1 error generated.
make: *** [tensor.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/dewayne/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/torch-rb-0.6.0 for inspection.
Results logged to /Users/dewayne/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/extensions/x86_64-darwin-19/3.0.0/torch-rb-0.6.0/gem_make.out
13:17:19 3.0.0p0  s5:~ [1] $

**Comment by ankane** [comment]
Hey @MadBomber, thanks for reporting. What version of LibTorch are you using?

**Comment by MadBomber** [comment]
You are right.  Sorry I should have caught that.  brew told me that I had version 1.7.1_1 installed.  I did a brew upgrade libtorch which installed version 1.8.1 which allowed the gem ins torch-rb to complete successfully.

**Comment by MadBomber** [comment]
FYI  alias brewski='brew update && brew upgrade && brew cleanup; brew doctor'

Running brewski on a weekly basis should be a habit.
