### ISSUE TITLE
Compatibility table: more informations

### ISSUE THREAD

**Issue by lfuszara1** [ankane/torch.rb#23]
Can you add to compatibility table libtorch versions information like availability without cuda (cpu only), with version of cuda (10.2 or 11.1 for 1.8.1 version of libtorch) and in future ROCm compatibility information?

I copied from Dockerfile installation instruction of torch.rb and finally it works on Ubuntu 20.10.

**Comment by ankane** [comment]
Hey @lfuszara1, Torch.rb should work with the CPU and CUDA versions.
