### ISSUE TITLE
failing on libtorch version

### ISSUE THREAD

**Issue by taf2** [ankane/torch.rb#34]
./utils.h:8:1: error: static_assert failed due to requirement '1 == 1 && 9 == 11' "Incompatible LibTorch version"

**Comment by orlando-labs** [comment]
Hi, @taf2, you are trying to build torch-rb against wrong version of libtorch. If you are trying to build actual at the moment torch-rb version 0.10.1 then you must have libtorch 1.11.0. Looks like your libtorch version is 1.9.*

**Comment by taf2** [comment]
@orlando-labs thanks - just ran brew install libtorch and got that older version... i'm running brew update now to see if i can get the newer version.

**Comment by orlando-labs** [comment]
Actual brew should do the trick
```bash
orlylabs@MacBook-Pro ~ % brew upgrade libtorch
Warning: libtorch 1.11.0 already installed
```

**Comment by taf2** [comment]
Yes this worked!   I also noticed when compiling with brew on linux... i had issues with LD_LIBRARY_PATH and CXXFLAGS, since by default brew linux puts things in /home/linuxbrew/... I'm at work now but can share details tonight... it's been usually nice to be able to use brew in mac and linux...

**Comment by ankane** [comment]
Hey @taf2, thanks for sharing. For Homebrew on Linux, you'll need to run:

```sh
bundle config build.torch-rb --with-torch-dir=/home/linuxbrew/.linuxbrew
```

before installing the gem. I've added it to the readme in the commit above.

**Comment by taf2** [comment]
@ankane thanks that worked - much easier thank hacking env vars thank you!

**Comment by ankane** [comment]
For future readers: Torch.rb now checks `/home/linuxbrew/.linuxbrew`, so no additional config is needed.
