### ISSUE TITLE
Missing `Torch::Generator`

### ISSUE THREAD

**Issue by c4lliope** [ankane/torch.rb#36]
In PyTorch I can use a random generator, such as:

```python
g = torch.Generator().manual_seed(2147483647)
p = [0.2, 0.6, 0.2]
ix = torch.multinomial(p, num_samples=1, replacement=True,generator=g).item()

```

Is there a recommended approach for using the generator, including methods like `multinomial`?

**Comment by ankane** [comment]
Hey @c4lliope, thanks for reporting! Added in the commit above (note that `p` must be a tensor in the latest PyTorch).

**Comment by ankane** [comment]
No problem. Let me know if you run into anything else that's missing.
