### ISSUE TITLE
Does touch.rb be able to running Core ML model ?

### ISSUE THREAD

**Issue by Eric-Guo** [ankane/torch.rb#38]
https://github.com/apple/ml-stable-diffusion#-image-generation-with-python

I like ruby and plan to rebuild web ui in Rails as side project, so I want to know.

**Comment by ankane** [comment]
Hi @Eric-Guo, it's not currently possible to convert Torch.rb models to Core ML (this requires [model tracing](https://coremltools.readme.io/docs/pytorch-conversion) with `torch.jit.trace`, which isn't currently supported, but happy to review a PR if someone wants to add it).
