### ISSUE TITLE
torch.rb not installing on Ubuntu 23.04 w. 3.2.2

### ISSUE THREAD

**Issue by jcasu** [ankane/torch.rb#43]
installed libtorch-dev, etc...
gem isn't finding libtorch (see below)

any pointers would be helpful.

tnx

--------------------------------------------------------------

john@enterprise:~$ gem install torch-rb
Building native extensions. This could take a while...
ERROR:  Error installing torch-rb:
	ERROR: Failed to build gem native extension.

    current directory: /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/torch-rb-0.13.2/ext/torch
/home/john/.rbenv/versions/3.2.2/bin/ruby extconf.rb
checking for rice/rice.hpp in /home/john/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rice-4.1.0/include... yes
checking for -lstdc++... yes
LibTorch not found
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

**Comment by ankane** [comment]
Hi @jcasu, try [these instructions](https://github.com/ankane/torch.rb#libtorch-installation) (use `--with-torch-dir` to specify the location). Note that the latest version requires LibTorch 2, while `libtorch-dev` provides 1.13.

**Comment by jcasu** [comment]
I tried that 1st, but it didn't seem to do anything.

I unpacked the zip from pytorch.org & pointed bundle to the directory called libtorch.

Did the bundle command, and it returned immediately.
No gem installed (I should expect that, right?)

fwiw, on my mac, doing brew install pytorch & then gem install torch-rb works flawlessly. likewise w. installing all the other torch* gems

thanks

-john
________________________________

**Comment by ankane** [comment]
You'll want to run `bundle install` after setting `bundle config`.

**Comment by jcasu** [comment]
ok...

tnx.
________________________________
