### ISSUE TITLE
torch.rb does not work on TruffleRuby

### ISSUE THREAD

**Issue by mtortonesi** [ankane/torch.rb#45]
I am trying to get torch.rb working with TruffleRuby (version truffleruby+graalvm-23.0.0 installed with rbenv+ruby_build on a M1 MacBookPro), but unfortunately when I launch the following TensorOption instantiation command:

<pre>
bundle exec ruby -e 'require "torch"; Torch::TensorOptions.new(1,2,3)'
</pre>

I get the following error:

<pre>
/Users/mauro/code/test/truffleruby/reinforce/vendor/bundle/truffleruby/3.1.3.23.0.0/gems/rice-4.1.0/include/rice/rice.hpp:4094:in `call': External LLVMFunction rb_frame_method_id_and_class cannot be found. (Polyglot::ForeignException)
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/truffle/truffle/cext_ruby.rb:41:in `<unknown>'
	from /Users/mauro/.rbenv/versions/truffleruby+graalvm-23.0.0/graalvm/Contents/Home/languages/ruby/lib/truffle/truffle/cext_ruby.rb:41:in `Torch::TensorOptions#initialize'
</pre>

I would like to help fixing this, but I really wouldn't know where to start. Any suggestions?

(Cross-reference with [this issue](https://github.com/oracle/truffleruby/issues/3205) on the TruffleRuby repo.)

**Comment by ankane** [comment]
Hi @mtortonesi, TruffleRuby isn't supported, and I don't really have the expertise to help with this. I think the first step would be getting Rice working with TruffleRuby, as the test suite [currently fails](https://github.com/ankane/rice/actions/runs/5844216804/job/15847095945).

**Comment by mtortonesi** [comment]
FYI, I just submitted oracle/truffleruby#3363, that implements the rb_frame_method_and_id in Truffleruby. The patch seems to get rice, and in turn torch.rb, to work with Truffleruby. 

(See also https://github.com/oracle/truffleruby/issues/3357.)

**Comment by ankane** [comment]
Great, thanks @mtortonesi
