### ISSUE TITLE
Docs: Undefined method `T` for `tensor`

### ISSUE THREAD

**Issue by bockets** [ankane/torch.rb#46]
https://github.com/ankane/torch.rb/blob/b0fa9a17671e0b04e8529ea439601c831e087e3a/tutorials/blitz/tensors.md?plain=1#L192

Looks like a typo, but the next part of the line has `tensor.t`, so I'm not entirely sure.

**Comment by ankane** [comment]
Hi @bockets, that's the correct output, but fixed syntax highlighting for the block.

**Comment by ankane** [comment]
Sorry, I see what you're saying now. Updated in the commit above.
