### ISSUE TITLE
`pipx` Path and Homebrew Issues

### ISSUE THREAD

**Issue by henrikbjorn** [ankane/torch.rb#55]
Trying to use `transformers-rb` and running into issues installing `torch-rb` since the homebrew `pytorch` package is `2.2.0`.

Instead I had to install with `pipx` and set the `--with-torch-dir` to `~/.local/pipx/venvs/torch/lib/python3.12/site-packages/torch`

Can that be auto discovered?

Thanks for the library :)

**Comment by ankane** [comment]
Thanks @henrikbjorn, updated the instructions in the commit above.
